### ISSUE TITLE
Unable to cancel bluebird promise

### ISSUE THREAD

**Issue by JJCella** [mike-marcacci/node-redlock#85] opened 2021-01-15 10:56 UTC
redlock: 4.2.0
ioredis: 4.19.4

Hi, I'm trying to use node-redlock with retryCount=-1. In order to gracefully shutdown my app, I'm quitting all my redis clients but **lockRed.lock()** promise is never rejected and continue to loop forever. 

**_'clientError_**' event is called forever with error `'Error: Connection is closed'`

Is there a way to cancel this Promise  ? I tried to cancel it before quitting redis and in 'clientError' event callback

[https://github.com/mike-marcacci/node-redlock/blob/870778cd520f9649e80f74fa755ee0f12519c683/redlock.js#L428](https://github.com/mike-marcacci/node-redlock/blob/870778cd520f9649e80f74fa755ee0f12519c683/redlock.js#L428)

Is the setTimeout preventing me from doing so ?

**Comment by mike-marcacci** [comment] 2021-11-26 17:20
There is no mechanism in the promise spec for cancelation. However, I'm not against providing a mechanism here in redlock, probably using the AbortController standard

I'm going to close this as a duplicate of #86 (I know you posted here a day before that was opened, though 😉)

**Closed by mike-marcacci** 2021-11-26 17:20 UTC
